/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/buses` | `/buses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notificationsScreen` | `/notificationsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/prices` | `/prices`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trains` | `/trains`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/buses` | `/buses`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/notificationsScreen` | `/notificationsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/prices` | `/prices`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/trains` | `/trains`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/buses${`?${string}` | `#${string}` | ''}` | `/buses${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/notificationsScreen${`?${string}` | `#${string}` | ''}` | `/notificationsScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/prices${`?${string}` | `#${string}` | ''}` | `/prices${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/trains${`?${string}` | `#${string}` | ''}` | `/trains${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/buses` | `/buses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notificationsScreen` | `/notificationsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/prices` | `/prices`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trains` | `/trains`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
